//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City_mend.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("City_mend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  *******       **      *******                                        **                         **     **                      
        ////**////**     */ *    /**////**    ******                            /**                        /**    //                       
        ////**    /**   / **     /**    /**  /**///**   ******    ******        /**   **   **    *****    ******   **    ******    ******* 
        ////**    /**    */ * *  /**    /**  /**  /**  //**//*   **////**    ******  /**  /**   **///**  ///**/   /**   **////**  //* [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на                                                 
        ///                                                                 +-------------------------------+
        ///                                                                 |                               |
        ///                                                                 |           City-mend           |
        ///                                                                 |                               |
        ///                                                               [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на                                                                     
        ///                                                                 #  
        ///                ###     ###     ###      ##     ###     ##      ### 
        ///                # #     #       ##       #      ##      # #      #  
        ///                ###     #       ###     ##      ###     # #      ## 
        ///                #                                                   .
        /// </summary>
        internal static string present {
            get {
                return ResourceManager.GetString("present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///+-------------------------+
        ///|                         |
        ///|        City-mend        |
        ///|                         |
        ///| +---------------------+ |
        ///| | Основные показатели | |
        ///| +---------------------+ |
        ///|                         |
        ///| +---------------------+ |
        ///| |       наука(i)      | |
        ///| +---------------------+ |
        ///| +---------------------+ |
        ///| |                     | |
        ///| | уровень деревни:    | |
        ///| |                     | |
        ///| +---------------------+ |
        ///| |                     | |
        ///| | жители:       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string базовые_показатели {
            get {
                return ResourceManager.GetString("базовые_показатели", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///+-------------------------+
        ///|                         |
        ///|        City-mend        |
        ///|                         |
        ///| +---------------------+ |
        ///| | Основные показатели | |
        ///| +---------------------+ |
        ///|                         |
        ///| +---------------------+ |
        ///| |       наука(i)      | |
        ///| +---------------------+ |
        ///| +---------------------+ |
        ///| |                     | |
        ///| | уровень города:     | |
        ///| |                     | |
        ///| +---------------------+ |
        ///| |                     | |
        ///| | жители:       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string базовые_показатели__город_ {
            get {
                return ResourceManager.GetString("базовые_показатели__город_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///            						                                                                                                                         
        ///          .g8&quot;&quot;&quot;bgd   db    mm                                                               `7MM  
        ///        .dP&apos;     `M         MM                                                                 MM  
        ///        dM&apos;       ` `7MM  mmMMmm  `7M&apos;   `MF&apos;    `7MMpMMMb.pMMMb.   .gP&quot;Ya  `7MMpMMMb.    ,M&quot;&quot;bMM  
        ///        MM            MM    MM      VA   ,V        MM    MM    MM  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string вар5 {
            get {
                return ResourceManager.GetString("вар5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    +-----------------------------------------------------------------------------------------------------------------------------------------------------+
        ///   |-----------------------------------------------------------------------------------------------------------------------------------------------------|
        ///   |-----------------------------------------------------------------------------------------------------------------------------------------------------|
        ///   |-|    X       X X  X X XXX      X        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string город_1_lvl_ {
            get {
                return ResourceManager.GetString("город_1_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-----------------------------------------------------------------------------------------------------+
        ///    |      X                                                                                              |
        ///    |     X X                                                                                             |
        ///    |    X   X                                                            XXXXXXXXXXXXXXXX                |
        ///    |    +---+                                                           X   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_1_lvl_ {
            get {
                return ResourceManager.GetString("деревня_1_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||      X                                                                                              ||
        ///    ||     X X                                                                                             ||
        ///    ||    X   X                                                      [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_2_lvl_ {
            get {
                return ResourceManager.GetString("деревня_2_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||      X                                                                                              ||
        ///    ||     X X                                                                                             ||
        ///    ||    X   X                                                      [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_3_lvl_ {
            get {
                return ResourceManager.GetString("деревня_3_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||    X                                                                                                ||
        ///    ||   X X                                                                                               ||
        ///    ||  X   X                                                        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_4_lvl_ {
            get {
                return ResourceManager.GetString("деревня_4_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||    X                                                                                                ||
        ///    ||   X X                                                                                               ||
        ///    ||  X   X                                                        [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_5_lvl_ {
            get {
                return ResourceManager.GetString("деревня_5_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||    X                         X                                                               X      ||
        ///    ||   X X                       X X                           X                                 X X     ||
        ///    ||  X   X                     X   X                         X X  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_6_lvl_ {
            get {
                return ResourceManager.GetString("деревня_6_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     +-------------------------------------------------------------------------------------------------------+
        ///    |-------------------------------------------------------------------------------------------------------|
        ///    ||    X       X X  X X XXX      X                          XXXX                                 X      ||
        ///    ||   X X     +-------------+   X X                        X    X                               X X     ||
        ///    ||  X   X    | || || |-----|  X   X                      X       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string деревня_7_lvl_ {
            get {
                return ResourceManager.GetString("деревня_7_lvl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream фон_музыка_меню_ {
            get {
                return ResourceManager.GetStream("фон_музыка_меню_", resourceCulture);
            }
        }
    }
}
